name: "Terraform"

on:
  push:
    branches:
      - master
      - main
      - develop
      - "feature/**"
  pull_request:

permissions:
  contents: read

jobs:
  terraform:
    name: "Terraform (${{ matrix.workdir }})"
    runs-on: ubuntu-latest
    environment: production

    strategy:
      fail-fast: false
      matrix:
        workdir:
          - examples/argo-cd
          - examples/fargate
          - examples/flux-cd
          - examples/jenkins
          - examples/on-demand
          - examples/spot

    defaults:
      run:
        shell: bash
        working-directory: ${{ matrix.workdir }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init -upgrade -input=false

      - name: Terraform Format
        run: terraform fmt -check
